### ISSUE TITLE
SpatialMaxPooling Buffer

### ISSUE THREAD

**Issue by sid027** [fmassa/optimize-net#14]
Optimizing the network with optnet gives slightly different results compared to an unoptimized network - more colours usually - if SpatialMaxPooling buffer (line 256 init.lua) is reused. Disabling it, largely, does not effect memory savings but gives equivalent results as the unoptimized version.
Maybe you should look into it.

**Comment by fmassa** [comment]
Hi, thanks for opening this issue.
Are you using `SpatialMaxUnpooling`? That's the only reason I see that could lead to different results with `optnet`, as it's a non-standard way of using the modules and would require some special treatment.

**Comment by sid027** [comment]
Yes. It is part of the network. Of course, I can always switch to average pooling and the results are same for both optimized and unoptimized networks in this case.
Is it possible you can give options of specific buffers that could be switched on/off as inputs?

**Comment by fmassa** [comment]
That's a possibility, yes. But it would only be a workaround for the underlying problem, which is the best way of handling `SpatialMaxUnpooling`. If the output of `SpatialMaxPooling` as a table with the `output` and the `indices`, then it would naturally fit into `optnet`, but that is a huge breaking change. I'll give it a thought

**Comment by soumith** [comment]
@fmassa do one pass on the network. If you detect any SpatialMaxUnpooling modules, disable the SpatialMaxPooling optimizations

**Comment by fmassa** [comment]
@soumith Yeah, that seems a good solution, thanks for the tip.
Will work on that (together with the documentation asked by @nicholas-leonard long ago) today afterwork.

**Comment by fmassa** [comment]
Fixed via https://github.com/fmassa/optimize-net/pull/15
