### ISSUE TITLE
Adding Wide-Resnet Model

### ISSUE THREAD

**Issue by campbx** [fmassa/optimize-net#17]
Great library!  

I am interested in using @szagoruyko  's Wide Resnet model from here: https://github.com/szagoruyko/wide-residual-networks

Can I copy-paste the model to models.lua, or would it need some special case tuning?

Thanks!

**Comment by fmassa** [comment]
There is no need to copy-paste the model definition to `models.lua`.
`models.lua` only defines some baseline models to be tested for correctness in `test.lua`.

All you need to do is:
```lua
model, input = getMyModel() -- gets your model, either by loading or defining it
optnet = require 'optnet'
-- choose the options you want
optnet. optimizeMemory(model, input, {mode='training',inplace=false}) 
```
