### ISSUE TITLE
pyTorch compatibility?

### ISSUE THREAD

**Issue by TheodoreGalanos** [fmassa/optimize-net#30]
I am sorry for this question, I realize it is not an issue but I was wondering if there is compatibility with pyTorch and, if possible, could there be an example displaying their connection.

Thank you very much in advance.

Kind regards,
Theodore.

**Comment by fmassa** [comment]
Hi, thanks for your question.

PyTorch is implemented in a different way than Torch7.
Indeed, whenever a buffer gets out of scope in PyTorch, it's immediately freed, so memory use is very low.
Thus, PyTorch already implements efficient memory management, and the techniques used in here do not apply to PyTorch.
